version: '3.8'

services:
  devcontainer:
    image: ubuntu:latest
    volumes:
      - ..:/workspace
    working_dir: /workspace
    command: /bin/sh -c "while sleep 1000; do :; done"

  gateway:
    build:
      context: ../gateway
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  contact-microservice:
    build:
      context: ../contactship-microservice
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
